#Requires -Version 7.0
<#
.SYNOPSIS
    Creates the AVD Entra groups (design/avd/landing-zone.md section 5.2) and, optionally, the Arc onboarding service
    principal, through Microsoft Graph. Idempotent; -WhatIf is the default.
.DESCRIPTION
    Groups: grp-<org>-<token>-avd-azure / -azl / -hybrid (realm routing), -avd-users (union: holds the share role; its members are
    the users themselves, added directly by New-AvdDemoUsers.ps1, because Entra Kerberos does not expand nested groups), -avd-admins, and the dynamic device group grp-<org>-<token>-avd-devices
    (device.displayName -startsWith "<token>-avd-"). grp-<org>-<token>-lab-operators is owned by the Azure Local S0
    script and is only looked up here.
    With -IncludeArcOnboardingPrincipal the app registration + service principal spn-<org>-<token>-arc-onboard is
    created; its client secret is generated by Graph, written straight to the ops vault as
    <SecretNamePrefix>-arc-onboarding-spn-client-id / -secret (90-day expiry, five tags) and never printed. That part
    must run on the Windows jump server. The Azure RBAC for the principal is done by lz-avd IaC (arc_onboard_sp_object_id).
    Object ids (names and ids only, no secrets) are written to -OutputFile for the environment file.
.EXAMPLE
    ..New-AvdEntraGroups.ps1 -TenantId <id> -Org <org> -LabToken <lab>
.EXAMPLE
    .\New-AvdEntraGroups.ps1 -TenantId <id> -Org <org> -LabToken <lab> -IncludeArcOnboardingPrincipal -KeyVaultName <ops-key-vault> -SecretNamePrefix <org>-<lab> -Execute
#>
[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
param(
    [Parameter(Mandatory)][string]$TenantId,
    [Parameter(Mandatory)][string]$Org,
    [Parameter(Mandatory)][string]$LabToken,
    [hashtable]$GroupNames,
    [switch]$IncludeArcOnboardingPrincipal,
    [string]$ArcOnboardingPrincipalName,
    [string]$KeyVaultName,
    [string]$SecretNamePrefix,
    [string]$OwnerEmail,
    [int]$SecretExpiryDays = 90,
    [string]$OutputFile,
    [switch]$Execute
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'LzAvd.Common.ps1')

if (-not $Execute) { $WhatIfPreference = $true }

$defaultNames = @{
    azure     = "grp-$Org-$LabToken-avd-azure"
    azl       = "grp-$Org-$LabToken-avd-azl"
    hybrid    = "grp-$Org-$LabToken-avd-hybrid"
    users     = "grp-$Org-$LabToken-avd-users"
    admins    = "grp-$Org-$LabToken-avd-admins"
    devices   = "grp-$Org-$LabToken-avd-devices"
    operators = "grp-$Org-$LabToken-lab-operators"
}
if ($GroupNames) { foreach ($k in $GroupNames.Keys) { $defaultNames[$k] = $GroupNames[$k] } }
if (-not $ArcOnboardingPrincipalName) { $ArcOnboardingPrincipalName = "spn-$Org-$LabToken-arc-onboard" }

foreach ($cmd in 'Connect-MgGraph', 'Get-MgGroup', 'New-MgGroup', 'New-MgGroupMember', 'Get-MgGroupMember') {
    if (-not (Test-LzAvdCommand -Name $cmd)) { throw "Microsoft.Graph cmdlet '$cmd' not available. Install-Module Microsoft.Graph.Groups, Microsoft.Graph.Applications, Microsoft.Graph.Authentication." }
}

$scopes = @('Group.ReadWrite.All', 'GroupMember.ReadWrite.All')
if ($IncludeArcOnboardingPrincipal) { $scopes += 'Application.ReadWrite.All' }
Connect-MgGraph -TenantId $TenantId -Scopes $scopes -NoWelcome

function Get-LzAvdGroupByName {
    param([Parameter(Mandatory)][string]$DisplayName)
    return (Get-MgGroup -Filter "displayName eq '$DisplayName'" -ConsistencyLevel eventual -Top 1)
}

function New-LzAvdSecurityGroup {
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)][string]$DisplayName,
        [string]$Description,
        [string]$DynamicRule
    )
    $existing = Get-LzAvdGroupByName -DisplayName $DisplayName
    if ($existing) {
        Write-LzAvdLog -Message "Group exists: $DisplayName ($($existing.Id))"
        return $existing
    }
    if (-not $PSCmdlet.ShouldProcess($DisplayName, 'Create Entra security group')) { return $null }
    $body = @{
        DisplayName     = $DisplayName
        Description     = $Description
        MailEnabled     = $false
        MailNickname    = ($DisplayName -replace '[^a-zA-Z0-9]', '')
        SecurityEnabled = $true
    }
    if ($DynamicRule) {
        $body.GroupTypes = @('DynamicMembership')
        $body.MembershipRule = $DynamicRule
        $body.MembershipRuleProcessingState = 'On'
    }
    $created = New-MgGroup @body
    Write-LzAvdLog -Message "Created group $DisplayName ($($created.Id))"
    return $created
}

$groups = @{}
$groups.azure = New-LzAvdSecurityGroup -DisplayName $defaultNames.azure -Description 'AVD realm: Azure session hosts (routing group)'
$groups.azl = New-LzAvdSecurityGroup -DisplayName $defaultNames.azl -Description 'AVD realm: Azure Local session hosts (routing group)'
$groups.hybrid = New-LzAvdSecurityGroup -DisplayName $defaultNames.hybrid -Description 'AVD realm: Hybrid Hyper-V session hosts (routing group)'
$groups.users = New-LzAvdSecurityGroup -DisplayName $defaultNames.users -Description 'AVD users union: FSLogix share role and Virtual Machine User Login'
$groups.admins = New-LzAvdSecurityGroup -DisplayName $defaultNames.admins -Description 'AVD admins: Desktop Virtualization Contributor, VM Administrator Login, share elevated contributor'
$groups.devices = New-LzAvdSecurityGroup -DisplayName $defaultNames.devices -Description 'AVD session-host devices (SSO target device group)' -DynamicRule "(device.displayName -startsWith `"$LabToken-avd-`")"
$groups.operators = Get-LzAvdGroupByName -DisplayName $defaultNames.operators
if (-not $groups.operators) { Write-LzAvdLog -Level Warning -Message "$($defaultNames.operators) not found; it is created by the Azure Local landing-zone S0 script." }

# The union group is NOT populated with the realm groups: Microsoft Entra Kerberos does not expand nested groups, so a user who
# is only a member of a realm group would get no share access and profile roaming would fail (conflict A7). Users are added to
# the union group directly by New-AvdDemoUsers.ps1 (-UsersGroupName); the realm groups only route the desktop (app-group role).

$principal = $null
if ($IncludeArcOnboardingPrincipal) {
    foreach ($cmd in 'Get-MgApplication', 'New-MgApplication', 'Get-MgServicePrincipal', 'New-MgServicePrincipal', 'Add-MgApplicationPassword') {
        if (-not (Test-LzAvdCommand -Name $cmd)) { throw "Microsoft.Graph.Applications cmdlet '$cmd' not available." }
    }
    $app = Get-MgApplication -Filter "displayName eq '$ArcOnboardingPrincipalName'" -Top 1
    if (-not $app -and $PSCmdlet.ShouldProcess($ArcOnboardingPrincipalName, 'Create app registration')) {
        $app = New-MgApplication -DisplayName $ArcOnboardingPrincipalName -SignInAudience 'AzureADMyOrg' -Notes 'Arc Connected Machine onboarding for AVD Hybrid hosts (HYB-06); least privilege on the Arc RG'
    }
    if ($app) {
        $principal = Get-MgServicePrincipal -Filter "appId eq '$($app.AppId)'" -Top 1
        if (-not $principal -and $PSCmdlet.ShouldProcess($ArcOnboardingPrincipalName, 'Create service principal')) {
            $principal = New-MgServicePrincipal -AppId $app.AppId
        }
    }
    if ($app -and $Execute) {
        if (-not $KeyVaultName -or -not $SecretNamePrefix) { throw '-KeyVaultName and -SecretNamePrefix are required to store the onboarding secret.' }
        Assert-LzAvdWindowsHost
        foreach ($cmd in 'Set-AzKeyVaultSecret', 'Get-AzKeyVaultSecret') { if (-not (Test-LzAvdCommand -Name $cmd)) { throw "Az.KeyVault cmdlet '$cmd' not available." } }
        $secretName = "$SecretNamePrefix-arc-onboarding-spn-secret"
        $clientIdName = "$SecretNamePrefix-arc-onboarding-spn-client-id"
        $existingSecret = Get-AzKeyVaultSecret -VaultName $KeyVaultName -Name $secretName -ErrorAction SilentlyContinue
        if ($existingSecret -and -not $existingSecret.Expires -lt (Get-Date)) {
            Write-LzAvdLog -Message "Vault secret $secretName already present and not expired; not rotating."
        }
        elseif ($PSCmdlet.ShouldProcess("$KeyVaultName/$secretName", 'Generate client secret and store in Key Vault')) {
            $expires = (Get-Date).ToUniversalTime().AddDays($SecretExpiryDays)
            $credential = Add-MgApplicationPassword -ApplicationId $app.Id -PasswordCredential @{ DisplayName = "lz-avd $(Get-Date -Format yyyyMMdd)"; EndDateTime = $expires }
            $secretChars = $credential.SecretText.ToCharArray()
            $credential = $null
            $tags = @{ owner = $OwnerEmail; project = $LabToken; 'rotation-days' = "$SecretExpiryDays"; 'managed-by' = 'script'; lifecycle = 'temporary' }
            try {
                [void](Set-AzKeyVaultSecret -VaultName $KeyVaultName -Name $clientIdName -SecretValue (ConvertTo-LzAvdSecureString -Characters $app.AppId.ToCharArray()) -Expires $expires -ContentType 'client-id' -Tag $tags)
                [void](Set-AzKeyVaultSecret -VaultName $KeyVaultName -Name $secretName -SecretValue (ConvertTo-LzAvdSecureString -Characters $secretChars) -Expires $expires -ContentType 'secret' -Tag $tags)
            }
            finally {
                Clear-LzAvdCharArray -Characters $secretChars -Confirm:$false
            }
            Write-LzAvdLog -Message "Stored $clientIdName and $secretName in $KeyVaultName (values not shown)."
        }
    }
}

$result = [ordered]@{
    tenant_id        = $TenantId
    group_object_ids = [ordered]@{
        avd_azure     = if ($groups.azure) { $groups.azure.Id } else { $null }
        avd_azl       = if ($groups.azl) { $groups.azl.Id } else { $null }
        avd_hybrid    = if ($groups.hybrid) { $groups.hybrid.Id } else { $null }
        avd_users     = if ($groups.users) { $groups.users.Id } else { $null }
        avd_admins    = if ($groups.admins) { $groups.admins.Id } else { $null }
        avd_devices   = if ($groups.devices) { $groups.devices.Id } else { $null }
        lab_operators = if ($groups.operators) { $groups.operators.Id } else { $null }
    }
    arc_onboard_sp_object_id = if ($principal) { $principal.Id } else { '' }
}
if ($OutputFile) {
    $result | ConvertTo-Json -Depth 4 | Set-Content -Path $OutputFile -Encoding utf8 -WhatIf:$false
    Write-LzAvdLog -Message "Wrote object ids to $OutputFile (ids only)."
}
[pscustomobject]$result
